// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from "@hey-api/client-fetch"
import type { CreateUserError, CreateUserResponse } from "./types.gen"

/**
 * Create User
 */
export const createUser = (options?: Options) => {
  return (options?.client ?? client).get<CreateUserResponse, CreateUserError>({
    ...options,
    url: "/api/v1/",
  })
}
