// This file is auto-generated by @hey-api/openapi-ts

export type CreateUserResponse = unknown

export type CreateUserError = unknown

export type $OpenApiTs = {
  "/api/v1/": {
    get: {
      res: {
        /**
         * Successful Response
         */
        "200": unknown
      }
    }
  }
}
